/* Generated by Yosys 0.68+ (git sha1 a5af9d690, Release, GNU /usr/bin/c++ 15.2.0) [github.com/The-OpenROAD-Project/yosys at HEAD] */

module riscv_cpu(clk, rst);
  input clk;
  wire clk;
  input rst;
  wire rst;
endmodule
